### ISSUE TITLE
SPPED UP MAN

### ISSUE THREAD

**Issue by Lirixingyi** [Jhonshen/leetcode#1]
ONE WEEK ONE SOLUTION?

**Comment by Jhonshen** [comment]
of course not,
![Uploading image.png…]()
copy code is a waste of time

**Comment by Jhonshen** [comment]
https://leetcode-cn.com/u/jhon-4/ follow my leetcode,i'll show you my work :)

**Comment by Lirixingyi** [comment]
i think i should where are we in this progress of this project , please align with me every day.
